# Generated by Django 4.2.4 on 2023-08-02 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phones_n_codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(validators=[django.core.validators.RegexValidator(message='Incorrect phone', regex='^8[0-9]{10}$')], verbose_name='phone')),
                ('self_code', models.CharField(max_length=6)),
                ('entered_code', models.CharField(max_length=6)),
            ],
        ),
    ]
